In [25]:
import csv, sqlite3
import pandas as pd 
import prettytable
prettytable.DEFAULT = 'DEFAULT' 

con = sqlite3.connect("my_data1.db")
cur = con.cursor()

In [26]:
import csv  , sqlite3
import prettytable

con = sqlite3.connect('my_data1.db')
cur = con.cursor()

In [27]:
%load_ext sql

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

In [28]:
%sql sqlite:///my_data1.db

In [29]:
df = pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_2/data/Spacex.csv")
df.to_sql("SPACEXTBL", con, if_exists='replace', index=False,method="multi")

101

In [30]:
df.head()

,Date,Time (UTC),Booster_Version,Launch_Site,Payload,PAYLOAD_MASS__KG_,Orbit,Customer,Mission_Outcome,Landing_Outcome
0,2010-06-04,18:45:00,F9 v1.0 B0003,CCAFS LC-40,Dragon Spacecraft Qualification Unit,0,LEO,SpaceX,Success,Failure (parachute)
1,2010-12-08,15:43:00,F9 v1.0 B0004,CCAFS LC-40,"Dragon demo flight C1, two CubeSats, barrel of...",0,LEO (ISS),NASA (COTS) NRO,Success,Failure (parachute)
2,2012-05-22,7:44:00,F9 v1.0 B0005,CCAFS LC-40,Dragon demo flight C2,525,LEO (ISS),NASA (COTS),Success,No attempt
3,2012-10-08,0:35:00,F9 v1.0 B0006,CCAFS LC-40,SpaceX CRS-1,500,LEO (ISS),NASA (CRS),Success,No attempt
4,2013-03-01,15:10:00,F9 v1.0 B0007,CCAFS LC-40,SpaceX CRS-2,677,LEO (ISS),NASA (CRS),Success,No attempt

In [34]:
%sql DROP TABLE IF EXISTS SPACEXTABLE;

 * sqlite:///my_data1.db
Done.

[]

In [35]:
%sql create table SPACEXTABLE as select * from SPACEXTBL where Date is not null

 * sqlite:///my_data1.db
Done.

[]

In [43]:
##Mostrar los nombres de los sitios de lanzamiento únicos en la misión espacial
%sql  select distinct Launch_Site from SPACEXTABLE ;

 * sqlite:///my_data1.db
Done.

[('CCAFS LC-40',), ('VAFB SLC-4E',), ('KSC LC-39A',), ('CCAFS SLC-40',)]

In [50]:
## Mostrar 5 registros donde comienzan los sitios de lanzamiento con la cadena 'CCA' 
%sql select * from SPACEXTABLE  WHERE Launch_Site LIKE 'CCA%' LIMIT 3;

 * sqlite:///my_data1.db
Done.

[('2010-06-04', '18:45:00', 'F9 v1.0  B0003', 'CCAFS LC-40', 'Dragon Spacecraft Qualification Unit', 0, 'LEO', 'SpaceX', 'Success', 'Failure (parachute)'),
 ('2010-12-08', '15:43:00', 'F9 v1.0  B0004', 'CCAFS LC-40', 'Dragon demo flight C1, two CubeSats, barrel of Brouere cheese', 0, 'LEO (ISS)', 'NASA (COTS) NRO', 'Success', 'Failure (parachute)'),
 ('2012-05-22', '7:44:00', 'F9 v1.0  B0005', 'CCAFS LC-40', 'Dragon demo flight C2', 525, 'LEO (ISS)', 'NASA (COTS)', 'Success', 'No attempt')]

In [ ]:
## Tarea 3: Mostrar la masa total de carga útil transportada por los propulsores lanzados por la NASA (CRS)

In [60]:
%sql select sum(PAYLOAD_MASS__KG_) as 'Total Masa  ' from SPACEXTABLE where  Customer like 'NASA (CRS)%'

 * sqlite:///my_data1.db
Done.

[(48213,)]

In [61]:
## Tarea 4: Mostrar la masa media de carga útil transportada por el propulsor versión F9 v1.1
%sql select avg(PAYLOAD_MASS__KG_)  as 'total media  de Masa'from SPACEXTABLE where Booster_Version like 'F9 v1.1%'

 * sqlite:///my_data1.db
Done.

[(2534.6666666666665,)]

In [69]:
## Tarea 5: Enumera la fecha en que se logró el primer resultado exitoso de aterrizaje en la plataforma terrestre
%sql select min(date) as  'fecha primer resultado 'from SPACEXTABLE where Landing_Outcome like 'Success (ground pad)';

 * sqlite:///my_data1.db
Done.

[('2015-12-22',)]

In [79]:
##Tarea 6: Enumera los nombres de los propulsores que tienen éxito en naves dron y que tienen una carga útil 
##superior a 4000 pero inferior a 6000
%sql select  Booster_Version from SPACEXTABLE where Landing_Outcome like 'Success (drone ship)' and PAYLOAD_MASS__KG_  between 4000 and 6000;

 * sqlite:///my_data1.db
Done.

[('F9 FT B1022',), ('F9 FT B1026',), ('F9 FT  B1021.2',), ('F9 FT  B1031.2',)]

In [94]:
##Tarea 7: Enumera el número total de resultados exitosos y fallidos de misiones
%sql select  Mission_Outcome  , count(*)  from SPACEXTABLE  group by Mission_Outcome;

 * sqlite:///my_data1.db
Done.

[('Failure (in flight)', 1),
 ('Success', 98),
 ('Success ', 1),
 ('Success (payload status unclear)', 1)]

In [98]:
## Tarea 8: Enumera todos los booster_versions que han soportado la masa máxima de carga útil, usando una subconsulta
%sql select DISTINCT Booster_Version from  SPACEXTABLE WHERE PAYLOAD_MASS__KG_ ==  15600;

 * sqlite:///my_data1.db
Done.

[('F9 B5 B1048.4',),
 ('F9 B5 B1049.4',),
 ('F9 B5 B1051.3',),
 ('F9 B5 B1056.4',),
 ('F9 B5 B1048.5',),
 ('F9 B5 B1051.4',),
 ('F9 B5 B1049.5',),
 ('F9 B5 B1060.2 ',),
 ('F9 B5 B1058.3 ',),
 ('F9 B5 B1051.6',),
 ('F9 B5 B1060.3',),
 ('F9 B5 B1049.7 ',)]

In [102]:
##Tarea 9: Enumera los registros con el mes, landing_outcomes de fallo en naves dron, 
##booster_version y launch_site para el año 2015

%sql SELECT SUBSTR(Date, 6, 2) AS Month, Landing_Outcome, Booster_Version, Launch_Site FROM SPACEXTABLE WHERE SUBSTR(Date, 1, 4) = '2015' AND Landing_Outcome = 'Failure (drone ship)';

 * sqlite:///my_data1.db
Done.

[('01', 'Failure (drone ship)', 'F9 v1.1 B1012', 'CCAFS LC-40'),
 ('04', 'Failure (drone ship)', 'F9 v1.1 B1015', 'CCAFS LC-40')]

In [103]:
## Tarea 10: Clasifica el conteo de resultados de aterrizaje entre 2010-06-04 y 2017-03-20, en orden descendente
%sql SELECT Landing_Outcome, COUNT(*) AS Count FROM SPACEXTABLE WHERE Date BETWEEN '2010-06-04' AND '2017-03-20' GROUP BY Landing_Outcome ORDER BY Count DESC;

 * sqlite:///my_data1.db
Done.

[('No attempt', 10),
 ('Success (drone ship)', 5),
 ('Failure (drone ship)', 5),
 ('Success (ground pad)', 3),
 ('Controlled (ocean)', 3),
 ('Uncontrolled (ocean)', 2),
 ('Failure (parachute)', 2),
 ('Precluded (drone ship)', 1)]

In [105]:
df.head()

,Date,Time (UTC),Booster_Version,Launch_Site,Payload,PAYLOAD_MASS__KG_,Orbit,Customer,Mission_Outcome,Landing_Outcome
0,2010-06-04,18:45:00,F9 v1.0 B0003,CCAFS LC-40,Dragon Spacecraft Qualification Unit,0,LEO,SpaceX,Success,Failure (parachute)
1,2010-12-08,15:43:00,F9 v1.0 B0004,CCAFS LC-40,"Dragon demo flight C1, two CubeSats, barrel of...",0,LEO (ISS),NASA (COTS) NRO,Success,Failure (parachute)
2,2012-05-22,7:44:00,F9 v1.0 B0005,CCAFS LC-40,Dragon demo flight C2,525,LEO (ISS),NASA (COTS),Success,No attempt
3,2012-10-08,0:35:00,F9 v1.0 B0006,CCAFS LC-40,SpaceX CRS-1,500,LEO (ISS),NASA (CRS),Success,No attempt
4,2013-03-01,15:10:00,F9 v1.0 B0007,CCAFS LC-40,SpaceX CRS-2,677,LEO (ISS),NASA (CRS),Success,No attempt